In [19]:
class Character:
    def __init__(self):
        self.health=100
    def move(self):
        self.health-=10
    def checkHealth(self):
        print(self.health)
    
class Knight(Character):
    def __init__(self):
        super().__init__()
    def move(self):
        super().move()
        self.health-=5
    

In [20]:
kn = Knight()
kn.checkHealth()
kn.move()
kn.checkHealth()

100
85


In [21]:
ary =[[[1, 2, 3, 3], [2, 3, 4, 5], [1, 2, 3, 6]], [[1, 2, 3, 3], [2, 3, 4, 5], [1, 2, 3, 6]]]

In [22]:
import numpy as np
np.shape(ary)

(2, 3, 4)

In [23]:
mat = [[1,2,3],[2,3,3]]
np.shape(mat)

(2, 3)

In [26]:
np.random.randint(1,10)

5

In [27]:
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [31]:
np.split(x,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

### 실습1

In [36]:
import numpy as np

x = [i for i in range(1,10)]
y = [i for i in range(10,100,10)]

In [38]:
x = np.array(x)
y = np.array(y)

In [45]:
x=x.reshape(3,3)
y=y.reshape(3,3)

In [48]:
x+y

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [50]:
x.dot(y)

array([[ 300,  360,  420],
       [ 660,  810,  960],
       [1020, 1260, 1500]])

### 실습2

In [51]:
a = np.linspace(1,20,30)

In [52]:
a

array([ 1.        ,  1.65517241,  2.31034483,  2.96551724,  3.62068966,
        4.27586207,  4.93103448,  5.5862069 ,  6.24137931,  6.89655172,
        7.55172414,  8.20689655,  8.86206897,  9.51724138, 10.17241379,
       10.82758621, 11.48275862, 12.13793103, 12.79310345, 13.44827586,
       14.10344828, 14.75862069, 15.4137931 , 16.06896552, 16.72413793,
       17.37931034, 18.03448276, 18.68965517, 19.34482759, 20.        ])

In [53]:
a+10

array([11.        , 11.65517241, 12.31034483, 12.96551724, 13.62068966,
       14.27586207, 14.93103448, 15.5862069 , 16.24137931, 16.89655172,
       17.55172414, 18.20689655, 18.86206897, 19.51724138, 20.17241379,
       20.82758621, 21.48275862, 22.13793103, 22.79310345, 23.44827586,
       24.10344828, 24.75862069, 25.4137931 , 26.06896552, 26.72413793,
       27.37931034, 28.03448276, 28.68965517, 29.34482759, 30.        ])

### 실습3

In [60]:
import random
randoms = np.random.randint(1,100,size=(2,10,10))
randoms

array([[[59,  7, 17,  8, 84, 23, 43, 22, 10, 13],
        [58, 73, 11, 67, 53,  2, 41, 66, 60, 23],
        [75, 29,  8, 71, 36, 28, 36, 96, 58, 23],
        [92, 14,  3, 34, 11, 79, 36, 47, 51, 40],
        [66, 77, 30,  2,  3, 64, 33, 82,  5, 65],
        [14, 23, 88, 29, 56, 41, 88, 11, 90, 93],
        [68, 84, 78, 53, 19, 59,  4, 39, 62, 30],
        [89, 82, 26, 66, 28, 77, 18, 33, 39, 70],
        [ 1, 92, 73, 60, 60, 96, 62, 92, 94, 10],
        [61, 76, 49, 34, 14, 30,  1, 26, 98, 19]],

       [[29, 28, 41, 87, 34, 85, 54, 89,  8, 11],
        [18, 54, 96, 27,  7, 27, 89, 98, 78, 71],
        [ 7, 35, 64,  3, 31, 57, 63, 75, 51, 95],
        [88, 95, 32, 75,  3, 20, 92, 68, 48,  8],
        [65, 44, 75,  5, 74, 70, 22, 25, 61,  8],
        [78, 98, 55, 76,  6, 37,  5, 80, 14, 66],
        [41, 81, 32, 10, 43, 24,  7, 65, 67, 59],
        [19, 76, 62, 83, 34, 85, 25,  4, 82, 98],
        [96, 10, 69, 21, 88, 28, 49, 95, 46, 33],
        [71, 74, 20, 42, 89,  9, 57, 41, 65, 97]

In [61]:
np.shape(randoms)

(2, 10, 10)

In [62]:
randoms = np.where(randoms>=50,1,2)

In [63]:
randoms

array([[[1, 2, 2, 2, 1, 2, 2, 2, 2, 2],
        [1, 1, 2, 1, 1, 2, 2, 1, 1, 2],
        [1, 2, 2, 1, 2, 2, 2, 1, 1, 2],
        [1, 2, 2, 2, 2, 1, 2, 2, 1, 2],
        [1, 1, 2, 2, 2, 1, 2, 1, 2, 1],
        [2, 2, 1, 2, 1, 2, 1, 2, 1, 1],
        [1, 1, 1, 1, 2, 1, 2, 2, 1, 2],
        [1, 1, 2, 1, 2, 1, 2, 2, 2, 1],
        [2, 1, 1, 1, 1, 1, 1, 1, 1, 2],
        [1, 1, 2, 2, 2, 2, 2, 2, 1, 2]],

       [[2, 2, 2, 1, 2, 1, 1, 1, 2, 2],
        [2, 1, 1, 2, 2, 2, 1, 1, 1, 1],
        [2, 2, 1, 2, 2, 1, 1, 1, 1, 1],
        [1, 1, 2, 1, 2, 2, 1, 1, 2, 2],
        [1, 2, 1, 2, 1, 1, 2, 2, 1, 2],
        [1, 1, 1, 1, 2, 2, 2, 1, 2, 1],
        [2, 1, 2, 2, 2, 2, 2, 1, 1, 1],
        [2, 1, 1, 1, 2, 1, 2, 2, 1, 1],
        [1, 2, 1, 2, 1, 2, 2, 1, 2, 2],
        [1, 1, 2, 2, 1, 2, 1, 2, 1, 1]]])

In [68]:
randoms[1:2,5:10,5:10]

array([[[2, 2, 1, 2, 1],
        [2, 2, 1, 1, 1],
        [1, 2, 2, 1, 1],
        [2, 2, 1, 2, 2],
        [2, 1, 2, 1, 1]]])

# pandas

In [69]:
import pandas as pd

In [70]:
x = [1,2,3,4,5]
s = pd.Series(x)
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [71]:
print(s.index)

RangeIndex(start=0, stop=5, step=1)


In [72]:
s.values

array([1, 2, 3, 4, 5], dtype=int64)

In [73]:
type(s.values)

numpy.ndarray

In [76]:
s = pd.Series(x, index = ['a','b','c','d','야호'])  #인덱스를 바꿔준다

In [77]:
s

a     1
b     2
c     3
d     4
야호    5
dtype: int64

In [79]:
s['야호']

5

In [80]:
s[4] # 기본 인덱스는 가지고 있다

5

In [81]:
s[['b','d']] #인덱스 여러개를 가지고 가져올 때는 대괄호로 한번 더 묶어서 가지고 온다

b    2
d    4
dtype: int64

In [82]:
x={"수학":90, "영어":80,"과학":95,"미술":80}
x=pd.Series(x)

In [83]:
x

수학    90
영어    80
과학    95
미술    80
dtype: int64

In [84]:
x.index

Index(['수학', '영어', '과학', '미술'], dtype='object')

In [86]:
x['수학':'과학'] #인덱스가 마지막을 포함하는게 좀 다르네...!

수학    90
영어    80
과학    95
dtype: int64